name: Upload FireLens Image to Prod ECR

on:
  workflow_dispatch:
    inputs:
      ACCOUNT_ID_VAR:
        description: "Target AWS account ID (prod)"
        required: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  PROD_ACCOUNT: ${{ inputs.ACCOUNT_ID_VAR }}
  IMAGE_NAME: images/firelens
  TAG: latest
  AWS_REGION: il-central-1
  INFRA_ACCOUNT_ID: "014498627927"

jobs:
  push-firelens:
    runs-on: codebuild-gh-runner-infrastructure-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials - Federated Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: il-central-1
          role-to-assume: arn:aws:iam::${{ env.INFRA_ACCOUNT_ID }}:role/wl-cicd-infrastructure-codebuild-role-${{ inputs.ACCOUNT_ID_VAR }}
          role-session-name: GitHubActions-Test

      - name: Configure AWS Credentials - Infra Execution Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ inputs.ACCOUNT_ID_VAR }}:role/wl-cicd-infrastructure-execution-role
          role-chaining: true
          role-session-name: GitHubActions-Test

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "$IMAGE_NAME" --region "$AWS_REGION" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$IMAGE_NAME" --region "$AWS_REGION"

      - name: Login to prod ECR
        run: |
          aws ecr get-login-password --region "$AWS_REGION" | \
          docker login --username AWS --password-stdin "$PROD_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Build and push custom FireLens image
        working-directory: firelens
        run: |
          docker build -t "$PROD_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$TAG" .
          docker push "$PROD_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$TAG"
