name: 'Client Simulator CD'

on:
  repository_dispatch:
    types: [ deploy-simulator ]

permissions:
  id-token: write
  contents: write
  actions: read
  pull-requests: write

env:
  tg_version: "0.60.1"
  AWS_REGION: "il-central-1"
  IMAGE_TAG: "${{ github.event.client_payload.image_tag }}"

jobs:
  deploy-last-image:
    runs-on: codebuild-gh-runner-infrastructure-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - name: 0.1 - Setup Python
      uses: actions/setup-python@v4

    - name: 0.1 - Setup GitHub CLI
      run: |
        echo "Installing GitHub CLI on Amazon Linux..."
        if command -v yum &>/dev/null; then
          curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo | sudo tee /etc/yum.repos.d/gh-cli.repo > /dev/null
          sudo yum install -y gh
        elif command -v dnf &>/dev/null; then
          curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo | sudo tee /etc/yum.repos.d/gh-cli.repo > /dev/null
          sudo dnf install -y gh
        else
          echo "❌ No compatible package manager (yum/dnf) found."
          exit 1
        fi

        gh --version

    - name: 1.0 - Generate GitHub App Token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    ##################################################
    ## Verify IMAGE_TAG input                       ##
    ##################################################
    - name: 1.0.1 - Verify IMAGE_TAG input
      run: |
        echo "✅ Received IMAGE_TAG: ${{ github.event.client_payload.image_tag }}"
        if [ -z "${{ github.event.client_payload.image_tag }}" ]; then
          echo "❌ Missing required input: IMAGE_TAG"
          exit 1
        fi

    - name: 1.1 - Checkout Infra Repo
      uses: actions/checkout@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}

    - name: Verify checkout location
      run: |
        echo "✅ Checked out ClickIDF/cap-infra-repo"
        pwd
        ls -la

    ##################################################
    ## Run simulator CD script                     ##
    ##################################################

    - name: 1.2 - Modify ECS task definitions and create PR
      working-directory: ./
      run: |
        python .github/workflows/simulator-cicd/simulator-dispatch-cd.py --ImageTag "${{ github.event.client_payload.image_tag }}"
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
