name: Terragrunt Import

on:
  workflow_dispatch:
    inputs:
      ACCOUNT_ID:
        description: "The AWS Account ID to import the resources to"
        required: true
        type: choice
        options:
          - "014498627927"
          - "993825007188"
          - "869935097196"
          - "619071333631"
          - "140023400154"
        default: "869935097196"
      FOLDER_PATH:
        description: "The path to the folder containing the terragrunt configuration files"
        required: true
        type: string
      
      RUNNER_TYPE:
        type: choice
        description: "Use infra for all, data for k8s/ path"
        required: true
        options:
          - infrastructure
          - data
      ENVIRONMENT:
        description: "Set only if u set RUNNER_TYPE to data. The environment to import the resources to"
        required: true
        type: choice
        options:
          - ''
          - dev
          - prod
        default: ''
      COMMAND:
        description: "The terragrunt command to run"
        required: true
        type: string
      GITHUB_ENVIRONMENT:
        description: "The GitHub environment to deploy to"
        required: true
        type: choice
        options:
          - int 
          - dev
          - preprod
          - prod
        default: int


env:
  DEV_HUB_ACCOUNT_ID: "014498638955"
  PROD_HUB_ACCOUNT_ID: "014498643213" 
  INFRA_ACCOUNT_ID: "014498627927"
  
  HUB_ACCOUNT_ID: ${{ inputs.ENVIRONMENT == 'dev' && '014498638955' || '014498643213' }}
  
  # Set 
  MAIN_ACCOUNT_ID: ${{ inputs.RUNNER_TYPE == 'infrastructure' && '014498627927' || inputs.ENVIRONMENT == 'dev' && '014498638955' || '014498643213' }}
  
  tg_version: "0.60.1"
  AWS_REGION: "il-central-1"
  TF_VERSION: "1.9.7"

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT
  pull-requests: write

jobs:

    terragrunt-import:
      # Pick runner by input
      # TODO find out dinamyc way to set runner labels from prod to dev 
      runs-on: [ "codebuild-gh-runner-${{ inputs.RUNNER_TYPE == 'infrastructure' && 'infrastructure' || format('orange-{0}', inputs.ENVIRONMENT) }}-${{ github.run_id }}-${{ github.run_attempt }}", "instance-type:small" ]
      environment: ${{ inputs.GITHUB_ENVIRONMENT }}
    #runs-on: codebuild-gh-runner-infrastructure-${{ github.run_id }}-${{ github.run_attempt }}
    # runs-on: codebuild-gh-runner-orange-${{ inputs.runner_ENV }}-${{ github.run_id }}-${{ github.run_attempt }}
      env:
          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
          AZURE_CLICK_TENANT_ID: ${{ vars.AZURE_CLICK_TENANT_ID }}
          ARGOCD_AZURE_CLIENT_ID: ${{ vars.ARGOCD_AZURE_CLIENT_ID }}
          ARGOCD_AZURE_CLIENT_SECRET: ${{ secrets.ARGOCD_AZURE_CLIENT_SECRET }}
          ARGOCD_ADMIN_GROUP_GUID: ${{ vars.ARGOCD_ADMIN_GROUP_GUID }}
          ARGOCD_DEVELOPER_GROUP_GUID: ${{ vars.ARGOCD_DEVELOPER_GROUP_GUID }}
          ARGOCD_NOC_GROUP_GUID: ${{ vars.ARGOCD_NOC_GROUP_GUID }}

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Configure aws credentials - Federated Role
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: il-central-1
            #TODO support both HUB and INFRA
            role-to-assume: arn:aws:iam::${{ env.MAIN_ACCOUNT_ID }}:role/wl-cicd-${{inputs.RUNNER_TYPE == 'infrastructure' && 'infrastructure' || 'build'}}-codebuild-role-${{ inputs.ACCOUNT_ID }}
            role-session-name: GitHubActions-Test

        - name: Configure AWS Credentials - Infra Execution Role
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: il-central-1
            role-to-assume: arn:aws:iam::${{ inputs.ACCOUNT_ID }}:role/wl-cicd-${{inputs.RUNNER_TYPE == 'infrastructure' && 'infrastructure' || 'build'}}-execution-role
            role-session-name: GitHubActions-Test
            role-chaining: true
        
        - name: Login Github CLI with App Token
          uses: actions/create-github-app-token@v3
          id: app-token
          with:
            client-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: ${{ github.repository_owner }}

        - name: Initialize Git with App Token
          run: |
            git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com".insteadOf https://github.com

        - name: Terraform setup
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "${{env.TF_VERSION}}"

        - name: Cache Terragrunt
          id: cache-terragrunt
          uses: actions/cache@v4
          with:
            path: /usr/local/bin/terragrunt
            key: ${{ runner.os }}-terragrunt-${{ env.tg_version }}

        - name: Install Terragrunt
          if: steps.cache-terragrunt.outputs.cache-hit != 'true'
          run: |
            echo "Installing Terragrunt"
            wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64
            chmod +x terragrunt_linux_amd64
            sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
            terragrunt --version

        - name: Verify Terragrunt Installation
          run: terragrunt --version

        - name: Finnaly run the command 😂
          run: |
            cd ${{ inputs.FOLDER_PATH }}
            ${{ inputs.COMMAND }}