name: Terragrunt Plan

on:
  workflow_call:
    inputs:
      ACCOUNT_ID_VAR:
        required: true
        type: string
      check_dir:
        required: true
        type: string
      HUB_ACCOUNT_ID:
        required: true
        type: string
      runner_ENV:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: false

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT
  pull-requests: write

env:
  tg_version: "0.60.1"
  AWS_REGION: "il-central-1"
  INFRA_ACCOUNT_ID: "014498627927"

jobs:
  plan:
    runs-on: codebuild-gh-runner-infrastructure-${{ github.run_id }}-${{ github.run_attempt }}
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure aws credentials - Federated Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: il-central-1
          role-to-assume: arn:aws:iam::${{ env.INFRA_ACCOUNT_ID }}:role/wl-cicd-infrastructure-codebuild-role-${{ inputs.ACCOUNT_ID_VAR }}
          role-session-name: GitHubActions-Test

      - name: Configure AWS Credentials - Infra Execution Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: il-central-1
          role-to-assume: arn:aws:iam::${{ inputs.ACCOUNT_ID_VAR }}:role/wl-cicd-infrastructure-execution-role
          role-session-name: GitHubActions-Test
          role-chaining: true

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.7"

      - name: Install Terragrunt
        run: |
          echo "Installing Terragrunt"
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version

      # Get the list of changed files in the PR
      - name: Get changed files
        id: changed-files
        run: |
          echo "the list of files from Inputs folder: ${{ inputs.check_dir }}"
          CHECK_DIR=$(echo "${{ inputs.check_dir }}")
          echo $CHECK_DIR
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt || true
          cat changed_files.txt
          # Filter only the 'terragrunt.hcl' files under the 'products' directory
          grep '^products/.*terragrunt\.hcl$' changed_files.txt | grep -v 'products/anan-magen/.*/shared/k8s/' > filtered_files.txt || true
          NON_K8S_DIRS=$(cat filtered_files.txt | grep "^products/anan-magen/il-central-1/$CHECK_DIR/") || true
          echo "NON_K8S_DIRS: $NON_K8S_DIRS"
          if [ -z "$NON_K8S_DIRS" ]; then
            echo "No Non-K8s directories found. Please check the directory paths or filter conditions."
            exit 0
          fi
          NON_K8S_DIRS_LIST=$(echo "$NON_K8S_DIRS" | tr '\n' ' ')
          echo "Found Non-K8s directories:"
          echo "$NON_K8S_DIRS_LIST"
          echo "$NON_K8S_DIRS_LIST" > filtered_files.txt
          if [ ! -s filtered_files.txt ]; then
            echo "No non-k8s relevant terragrunt.hcl files changed. Skipping plan."
            exit 0
          fi

          echo "Changed terragrunt.hcl files:"
          cat filtered_files.txt

        shell: bash

      - name: Run Terragrunt HCL Format on changed directories
        run: |
          while IFS= read -r file; do
            # Extract the directory path for the file (ignores the file itself)
            dir=$(dirname "$file")
            echo "Running Terragrunt HCL Format on $dir"

            # Run the Terragrunt hclfmt check for that directory
            terragrunt hclfmt --terragrunt-check --terragrunt-diff --terragrunt-working-dir "$dir"

          done < filtered_files.txt

      - name: Run Terragrunt plan
        id: plan
        env:
          MESSAGEDB_USER: ${{ secrets.MESSAGEDB_USER }}
          REPORTSDB_USER: ${{ secrets.REPORTSDB_USER }}
          SETTINGSDB_USER: ${{ secrets.SETTINGSDB_USER }}
          BROKER_USER_PROFILER_PP: ${{ secrets.BROKER_USER_PROFILER_PP }}
          BROKER_PASSWORD_PROFILER_PP: ${{ secrets.BROKER_PASSWORD_PROFILER_PP }}
          BROKER_USER_MONITOR_PP: ${{ secrets.BROKER_USER_MONITOR_PP }}
          BROKER_PASSWORD_MONITOR_PP: ${{ secrets.BROKER_PASSWORD_MONITOR_PP }}
          BROKER_USER_MASAL_GW_PP: ${{ secrets.BROKER_USER_MASAL_GW_PP }}
          BROKER_PASSWORD_MASAL_GW_PP: ${{ secrets.BROKER_PASSWORD_MASAL_GW_PP }}
          BROKER_USER_CLIENTAPI_PP: ${{ secrets.BROKER_USER_CLIENTAPI_PP }}
          BROKER_PASSWORD_CLIENTAPI_PP: ${{ secrets.BROKER_PASSWORD_CLIENTAPI_PP }}
          BROKER_USER_PROFILER: ${{ secrets.BROKER_USER_PROFILER }}
          BROKER_PASSWORD_PROFILER: ${{ secrets.BROKER_PASSWORD_PROFILER }}
          BROKER_USER_MONITOR: ${{ secrets.BROKER_USER_MONITOR }}
          BROKER_PASSWORD_MONITOR: ${{ secrets.BROKER_PASSWORD_MONITOR }}
          BROKER_USER_MASAL_GW: ${{ secrets.BROKER_USER_MASAL_GW }}
          BROKER_PASSWORD_MASAL_GW: ${{ secrets.BROKER_PASSWORD_MASAL_GW }}
          BROKER_USER_CLIENTAPI: ${{ secrets.BROKER_USER_CLIENTAPI }}
          BROKER_PASSWORD_CLIENTAPI: ${{ secrets.BROKER_PASSWORD_CLIENTAPI }}
          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
        run: |
          while IFS= read -r file; do
            # Get the directory of the changed file
            dir=$(dirname "$file")
            echo "Changing directory to: $dir"
            
            # Change to the directory where terragrunt.hcl is located
            pushd "$dir"
            
            # Print current directory for debugging
            echo "Running Terragrunt in directory: $(pwd)"
            current_plan_output=$(terragrunt plan -no-color 2>&1 | grep -v 'Initializing' | grep -v 'provider plugins' | sed 's/`/\\`/g' | sed 's/\$/\\$/g')
            plan_output+="**Terragrunt Plan Output for $dir:**\n\`\`\`\n$current_plan_output\n\`\`\`\n"
            popd
          done < filtered_files.txt

          echo "plan_output<<EOF" >> $GITHUB_ENV
          echo "$plan_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR
        uses: actions/github-script@v6
        env:
          PLAN: "${{ env.plan_output }}"
        id: plan-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Terraform Plan 📖 : \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('HCP Terraform Plan Output')
            });

            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  plan-k8s:
    runs-on: codebuild-gh-runner-orange-${{ inputs.runner_ENV }}-${{ github.run_id }}-${{ github.run_attempt }}
    environment: prod
    needs: [plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure aws credentials - Federated Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: il-central-1
          role-to-assume: arn:aws:iam::${{ inputs.HUB_ACCOUNT_ID }}:role/wl-cicd-build-codebuild-role-${{ inputs.ACCOUNT_ID_VAR }}

      - name: Configure AWS Credentials - Build Execution Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: il-central-1
          role-to-assume: arn:aws:iam::${{ inputs.ACCOUNT_ID_VAR }}:role/wl-cicd-build-execution-role
          role-chaining: true

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.7"

      - name: Install Terragrunt
        run: |
          echo "Installing Terragrunt"
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version

      - name: Get changed K8s files
        id: k8s-files
        run: |
          echo "the list of files from Inputs folder: ${{ inputs.check_dir }}"
          CHECK_DIR=$(echo "${{ inputs.check_dir }}")
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt || true
          echo "Changed changed terragrunt.hcl files:"
          cat changed_files.txt
          grep -E '^products/anan-magen/il-central-1/$CHECK_DIR/shared/k8s/.*terragrunt\.hcl$' changed_files.txt > k8s_files.txt || true
          echo "Changed k8s terragrunt.hcl files:"
          cat k8s_files.txt

          if [ ! -s k8s_files.txt ]; then
            echo "No K8s terragrunt.hcl files changed. Skipping K8s plan."
            exit 0
          fi

        shell: bash

      - name: Run Terragrunt HCL Format on changed K8s directories
        run: |
          while IFS= read -r file; do
            dir=$(dirname "$file")
            echo "Running Terragrunt HCL Format on $dir"

            # Run the Terragrunt hclfmt check for that directory
            terragrunt hclfmt --terragrunt-check --terragrunt-diff --terragrunt-working-dir "$dir"

          done < k8s_files.txt

      - name: Run Terragrunt Plan for K8s
        id: plan
        env:
          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
        run: |
          plan_output=""
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              dir=$(dirname "$file")
              echo "Changing directory to: $dir"
              pushd "$dir"
              echo "Running Terragrunt in directory: $(pwd)"
              current_plan_output=$(terragrunt plan -no-color 2>&1 | grep -v 'Initializing' | grep -v 'provider plugins' | sed 's/`/\\`/g' | sed 's/\$/\\$/g')
              plan_output+="**Terragrunt Plan Output for $dir:**\n\`\`\`\n$current_plan_output\n\`\`\`\n"
              popd
            fi  
          done < k8s_files.txt

          echo "plan_output<<EOF" >> $GITHUB_ENV
          echo "$plan_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR with K8s Plan
        uses: actions/github-script@v6
        env:
          PLAN: "${{ env.plan_output }}"
        id: plan-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### K8s Terragrunt Plan 📖

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('K8s Terragrunt Plan Output')
            });

            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
